//____________APP Actions____________
export const APP_SET_THEME = 'APP_SET_THEME';

//_______Authentication Actions_______
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';


//________Invoice Actions__________
export const INVOICE_START = 'INVOICE_START';
export const INVOICE_SUCCESS = 'INVOICE_SUCCESS';
export const INVOICE_FAIL = 'INVOICE_FAIL';
export const INVOICE_GET_ALL = 'INVOICE_GET_ALL';
export const INVOICE_SET_PAGE = 'INVOICE_SET_PAGE';
export const INVOICE_SET_PAGESIZE = 'INVOICE_SET_PAGESIZE';
export const INVOICE_SET_FILTERSQUERY = 'INVOICE_SET_FILTERSQUERY';
export const INVOICE_SET_QUICKFILTER = 'INVOICE_SET_QUICKFILTER';
export const INVOICE_UPDATE_FILTERING = 'INVOICE_UPDATE_FILTERING';
export const INVOICE_SET_SORTQUERY = 'INVOICE_SET_SORTQUERY';
export const INVOICE_SET_REVERSESORT = 'INVOICE_SET_REVERSESORT';
export const INVOICE_UPDATE_SHOWFILTERS = 'INVOICE_UPDATE_SHOW_FILTERS';
export const INVOICE_GET_DOCUMENT_FILE = 'INVOICE_GET_DOCUMENT_FILE';
export const INVOICE_SELECT_ROW = 'INVOICE_SELECT_ROW';
export const INVOICE_SELECT_ALL_ROWS = 'INVOICE_SELECT_ALL_ROWS';
export const INVOICE_GET_COMPRESSED_DOCUMENT = 'INVOICE_GET_COMPRESSED_DOCUMENT';
export const INVOICE_SET_IMPORT_ERRORS_COUNT = 'INVOICE_SET_IMPORT_ERRORS_COUNT';
//-------------------COMMANDEDEADLINEEXCEEDED---------------------//
export const COMMANDEDEADLINEEXCEEDED_START = 'COMMANDEDEADLINEEXCEEDED_START';
export const COMMANDEDEADLINEEXCEEDED_SUCCESS = 'COMMANDEDEADLINEEXCEEDED_SUCCESS';
export const COMMANDEDEADLINEEXCEEDED_FAIL = 'COMMANDEDEADLINEEXCEEDED_FAIL';
export const COMMANDEDEADLINEEXCEEDED_GET_ALL = 'COMMANDEDEADLINEEXCEEDED_GET_ALL';
export const COMMANDEDEADLINEEXCEEDED_SET_PAGE = 'COMMANDEDEADLINEEXCEEDED_SET_PAGE';
export const COMMANDEDEADLINEEXCEEDED_SET_PAGESIZE = 'COMMANDEDEADLINEEXCEEDED_SET_PAGESIZE';
export const COMMANDEDEADLINEEXCEEDED_SET_FILTERSQUERY = 'COMMANDEDEADLINEEXCEEDED_SET_FILTERSQUERY';
export const COMMANDEDEADLINEEXCEEDED_SET_QUICKFILTER = 'COMMANDEDEADLINEEXCEEDED_SET_QUICKFILTER';
export const COMMANDEDEADLINEEXCEEDED_UPDATE_FILTERING = 'COMMANDEDEADLINEEXCEEDED_UPDATE_FILTERING';
export const COMMANDEDEADLINEEXCEEDED_SET_SORTQUERY = 'COMMANDEDEADLINEEXCEEDED_SET_SORTQUERY';
export const COMMANDEDEADLINEEXCEEDED_SET_REVERSESORT = 'COMMANDEDEADLINEEXCEEDED_SET_REVERSESORT';
export const COMMANDEDEADLINEEXCEEDED_UPDATE_SHOWFILTERS = 'COMMANDEDEADLINEEXCEEDED_UPDATE_SHOW_FILTERS';
export const COMMANDEDEADLINEEXCEEDED_SELECT_ROW = 'COMMANDEDEADLINEEXCEEDED_SELECT_ROW';
export const COMMANDEDEADLINEEXCEEDED_SELECT_ALL_ROWS = 'COMMANDEDEADLINEEXCEEDED_SELECT_ALL_ROWS';
export const COMMANDEDEADLINEEXCEEDED_GET_COMPRESSED_DOCUMENT = 'COMMANDEDEADLINEEXCEEDED_GET_COMPRESSED_DOCUMENT';


export const COMMANDE_UPDATE_SHOWFILTERS= 'COMMANDE_UPDATE_SHOW_FILTERS';
export const COMMANDE_SET_QUICKFILTER="COMMANDE_SET_QUICKFILTER";
export const COMMANDE_SET_FILTERSQUERY="COMMANDE_SET_FILTERSQUERY";
export const COMMANDE_FAIL="COMMANDE_FAIL";
export const COMMANDE_SUCCESS="COMMANDE_SUCCESS";
export const COMMANDE_SET_PAGESIZE="COMMANDE_SET_PAGESIZE";
export const COMMANDE_SET_PAGE="COMMANDE_SET_PAGE";
export const COMMANDE_START="COMMANDE_START";
export const COMMANDE_SET_IMPORT_ERRORS_COUNT="COMMANDE_SET_IMPORT_ERRORS_COUNT";
export const COMMANDE_SELECT_ALL_ROWS="COMMANDE_SELECT_ALL_ROWS";
export const COMMANDE_SELECT_ROW="COMMANDE_SELECT_ROW";
export const COMMANDE_GET_DOCUMENT_FILE="COMMANDE_GET_DOCUMENT_FILE";
export const COMMANDE_SET_REVERSESORT="COMMANDE_SET_REVERSESORT";
export const COMMANDE_SET_SORTQUERY="COMMANDE_SET_SORTQUERY";
export const COMMANDEDETAIL_DATA_START = 'COMMANDEDETAIL_DATA_START'
export const COMMANDEDETAIL_DATA_SUCCESS = 'COMMANDEDETAIL_DATA_SUCCESS'
export const COMMANDEDETAIL_DATA_FAIL = 'COMMANDEDETAIL_DATA_FAIL'
//----------------invoice home client--------
export const INVOICECLIENT_START = 'INVOICECLIENT_START';
export const INVOICECLIENT_SUCCESS = 'INVOICECLIENT_SUCCESS';
export const INVOICECLIENT_FAIL = 'INVOICECLIENT_FAIL';
export const INVOICECLIENT_GET_ALL = 'INVOICECLIENT_GET_ALL';
export const INVOICECLIENT_SET_PAGE = 'INVOICECLIENT_SET_PAGE';
export const INVOICECLIENT_SET_PAGESIZE = 'INVOICECLIENT_SET_PAGESIZE';
export const INVOICECLIENT_SET_FILTERSQUERY = 'INVOICECLIENT_SET_FILTERSQUERY';
export const INVOICECLIENT_SET_QUICKFILTER = 'INVOICECLIENT_SET_QUICKFILTER';
export const INVOICECLIENT_UPDATE_FILTERING = 'INVOICECLIENT_UPDATE_FILTERING';
export const INVOICECLIENT_SET_SORTQUERY = 'INVOICECLIENT_SET_SORTQUERY';
export const INVOICECLIENT_SET_REVERSESORT = 'INVOICECLIENT_SET_REVERSESORT';
export const INVOICECLIENT_UPDATE_SHOWFILTERS = 'INVOICECLIENT_UPDATE_SHOW_FILTERS';
export const INVOICECLIENT_GET_DOCUMENT_FILE = 'INVOICECLIENT_GET_DOCUMENT_FILE';
export const INVOICECLIENT_SELECT_ROW = 'INVOICECLIENT_SELECT_ROW';
export const INVOICECLIENT_SELECT_ALL_ROWS = 'INVOICECLIENT_SELECT_ALL_ROWS';
export const INVOICECLIENT_GET_COMPRESSED_DOCUMENT = 'INVOICECLIENT_GET_COMPRESSED_DOCUMENT';
export const INVOICECLIENT_SET_IMPORT_ERRORS_COUNT = 'INVOICECLIENT_SET_IMPORT_ERRORS_COUNT';
//____________Clients Actions_________
export const CLIENTS_START = 'CLIENTS_START';
export const CLIENTS_SUCCESS = 'CLIENTS_SUCCESS';
export const CLIENTS_FAIL = 'CLIENTS_FAIL';
export const CLIENTS_GET_ALL = 'CLIENTS_GET_ALL';
export const CLIENTS_SET_PAGE = 'CLIENTS_SET_PAGE';
export const CLIENTS_SET_PAGESIZE = 'CLIENTS_SET_PAGESIZE';
export const CLIENTS_SET_FILTERSQUERY = 'CLIENTS_SET_FILTERSQUERY';
export const CLIENTS_UPDATE_FILTERING = 'CLIENTS_UPDATE_FILTERING';
export const CLIENTS_SET_SORTQUERY = 'CLIENTS_SET_SORTQUERY';
export const CLIENTS_SET_REVERSESORT = 'CLIENTS_SET_REVERSESORT';
export const CLIENTS_UPDATE_SHOWFILTERS = 'CLIENTS_UPDATE_SHOW_FILTERS';

//____________Documentation Actions_________
export const DOCUMENTATION_START = 'DOCUMENTATION_START';
export const DOCUMENTATION_SUCCESS = 'DOCUMENTATION_SUCCESS';
export const DOCUMENTATION_FAIL = 'DOCUMENTATION_FAIL';
export const DOCUMENTATION_GET_ALL = 'DOCUMENTATION_GET_ALL';
export const DOCUMENTATION_SET_PAGE = 'DOCUMENTATION_SET_PAGE';
export const DOCUMENTATION_SET_PAGESIZE = 'DOCUMENTATION_SET_PAGESIZE';
export const DOCUMENTATION_SET_FILTERSQUERY = 'DOCUMENTATION_SET_FILTERSQUERY';
export const DOCUMENTATION_UPDATE_FILTERING = 'DOCUMENTATION_UPDATE_FILTERING';
export const DOCUMENTATION_SET_SORTQUERY = 'DOCUMENTATION_SET_SORTQUERY';
export const DOCUMENTATION_SET_REVERSESORT = 'DOCUMENTATION_SET_REVERSESORT';
export const DOCUMENTATION_UPDATE_SHOWFILTERS = 'DOCUMENTATION_UPDATE_SHOWFILTERS';

//____________Entities Actions_________
export const ENTITIES_START = 'ENTITIES_START';
export const ENTITIES_SUCCESS = 'ENTITIES_SUCCESS';
export const ENTITIES_FAIL = 'ENTITIES_FAIL';
export const ENTITIES_GET_ALL = 'ENTITIES_GET_ALL';
export const ENTITIES_SET_PAGE = 'ENTITIES_SET_PAGE';
export const ENTITIES_SET_PAGESIZE = 'ENTITIES_SET_PAGESIZE';
export const ENTITIES_SET_FILTERSQUERY = 'ENTITIES_SET_FILTERSQUERY';
export const ENTITIES_UPDATE_FILTERING = 'ENTITIES_UPDATE_FILTERING';
export const ENTITIES_SET_SORTQUERY = 'ENTITIES_SET_SORTQUERY';
export const ENTITIES_SET_REVERSESORT = 'ENTITIES_SET_REVERSESORT';
export const ENTITIES_UPDATE_SHOWFILTERS = 'ENTITIES_UPDATE_SHOWFILTERS';
//________________ppf____________//
export const ENTITIESPPF_START = 'ENTITIESPPF_START';
export const ENTITIESPPF_SUCCESS = 'ENTITIESPPF_SUCCESS';
export const ENTITIESPPF_FAIL = 'ENTITIESPPF_FAIL';
export const ENTITIESPPF_GET_ALL = 'ENTITIESPPF_GET_ALL';
export const ENTITIESPPF_SET_PAGE = 'ENTITIESPPF_SET_PAGE';
export const ENTITIESPPF_SET_PAGESIZE = 'ENTITIESPPF_SET_PAGESIZE';
export const ENTITIESPPF_SET_FILTERSQUERY = 'ENTITIESPPF_SET_FILTERSQUERY';
export const ENTITIESPPF_UPDATE_FILTERING = 'ENTITIESPPF_UPDATE_FILTERING';
export const ENTITIESPPF_SET_SORTQUERY = 'ENTITIESPPF_SET_SORTQUERY';
export const ENTITIESPPF_SET_REVERSESORT = 'ENTITIESPPF_SET_REVERSESORT';
export const ENTITIESPPF_UPDATE_SHOWFILTERS = 'ENTITIESPPF_UPDATE_SHOWFILTERS';
export const ENTITIESPPF_SET_ENTITY_SUCCESS='ENTITIESPPF_SET_ENTITY_SUCCESS'

//________________echangePDP____________//

export const ECHANGEPDP_START = 'ECHANGEPDP_START';
export const ECHANGEPDP_SUCCESS = 'ECHANGEPDP_SUCCESS';
export const ECHANGEPDP_FAIL = 'ECHANGEPDP_FAIL';
export const ECHANGEPDP_GET_ALL = 'ECHANGEPDP_GET_ALL';
export const ECHANGEPDP_SET_PAGE = 'ECHANGEPDP_SET_PAGE';
export const ECHANGEPDP_SET_PAGESIZE = 'ECHANGEPDP_SET_PAGESIZE';
export const ECHANGEPDP_SET_FILTERSQUERY = 'ECHANGEPDP_SET_FILTERSQUERY';
export const ECHANGEPDP_UPDATE_FILTERING = 'ECHANGEPDP_UPDATE_FILTERING';
export const ECHANGEPDP_SET_SORTQUERY = 'ECHANGEPDP_SET_SORTQUERY';
export const ECHANGEPDP_SET_REVERSESORT = 'ECHANGEPDP_SET_REVERSESORT';
export const ECHANGEPDP_UPDATE_SHOWFILTERS = 'ECHANGEPDP_UPDATE_SHOWFILTERS';
export const ECHANGEPDP_SET_ENTITY_SUCCESS='ECHANGEPDP_SET_ENTITY_SUCCESS'

//____________Campaigns Actions_________
export const CAMPAIGNS_START = 'CAMPAIGNS_START';
export const CAMPAIGNS_SUCCESS = 'CAMPAIGNS_SUCCESS';
export const CAMPAIGNS_FAIL = 'CAMPAIGNS_FAIL';
export const CAMPAIGNS_GET_ALL = 'CAMPAIGNS_GET_ALL';
export const CAMPAIGNS_SET_PAGE = 'CAMPAIGNS_SET_PAGE';
export const CAMPAIGNS_SET_PAGESIZE = 'CAMPAIGNS_SET_PAGESIZE';
export const CAMPAIGNS_SET_FILTERSQUERY = 'CAMPAIGNS_SET_FILTERSQUERY';
export const CAMPAIGNS_UPDATE_FILTERING = 'CAMPAIGNS_UPDATE_FILTERING';
export const CAMPAIGNS_SET_SORTQUERY = 'CAMPAIGNS_SET_SORTQUERY';
export const CAMPAIGNS_SET_REVERSESORT = 'CAMPAIGNS_SET_REVERSESORT';
export const CAMPAIGNS_UPDATE_SHOWFILTERS = 'CAMPAIGNS_UPDATE_SHOWFILTERS';

//____________Suppliers Actions_________
export const SUPPLIERS_START = 'SUPPLIERS_START';
export const SUPPLIERS_SUCCESS = 'SUPPLIERS_SUCCESS';
export const SUPPLIERS_FAIL = 'SUPPLIERS_FAIL';
export const SUPPLIERS_GET_ALL = 'SUPPLIERS_GET_ALL';
export const SUPPLIERS_SET_PAGE = 'SUPPLIERS_SET_PAGE';
export const SUPPLIERS_SET_PAGESIZE = 'SUPPLIERS_SET_PAGESIZE';
export const SUPPLIERS_SET_FILTERSQUERY = 'SUPPLIERS_SET_FILTERSQUERY';
export const SUPPLIERS_UPDATE_FILTERING = 'SUPPLIERS_UPDATE_FILTERING';
export const SUPPLIERS_SET_SORTQUERY = 'SUPPLIERS_SET_SORTQUERY';
export const SUPPLIERS_SET_REVERSESORT = 'SUPPLIERS_SET_REVERSESORT';
export const SUPPLIERS_UPDATE_SHOWFILTERS = 'SUPPLIERS_UPDATE_SHOW_FILTERS';
export const SUPPLIERS_SEARCH_INPUT = 'SUPPLIERS_SEARCH_INPUT';
//____________reporting Actions_________
export const REPORTING_START = 'REPORTING_START';
export const REPORTING_SUCCESS = 'REPORTING_SUCCESS';
export const REPORTING_FAIL = 'REPORTING_FAIL';
export const REPORTING_SET_PAGESIZE = 'REPORTING_SET_PAGESIZE';


//____________Accountants Actions_________
export const ACCOUNTANTS_START = 'ACCOUNTANTS_START';
export const ACCOUNTANTS_SUCCESS = 'ACCOUNTANTS_SUCCESS';
export const ACCOUNTANTS_FAIL = 'ACCOUNTANTS_FAIL';
export const ACCOUNTANTS_GET_ALL = 'ACCOUNTANTS_GET_ALL';
export const ACCOUNTANTS_SET_PAGE = 'ACCOUNTANTS_SET_PAGE';
export const ACCOUNTANTS_SET_FILTERSQUERY = 'ACCOUNTANTS_SET_FILTERSQUERY';
export const ACCOUNTANTS_UPDATE_FILTERING = 'ACCOUNTANTS_UPDATE_FILTERING';
export const ACCOUNTANTS_SET_SORTQUERY = 'ACCOUNTANTS_SET_SORTQUERY';
export const ACCOUNTANTS_SET_REVERSESORT = 'ACCOUNTANTS_SET_REVERSESORT';
export const ACCOUNTANTS_UPDATE_SHOWFILTERS = 'ACCOUNTANTS_UPDATE_SHOW_FILTERS';

//___________Logs Actions_____________
export const LOGS_START = 'LOGS_START';
export const LOGS_SUCCESS = 'LOGS_SUCCESS';
export const LOGS_FAIL = 'LOGS_FAIL';
export const LOGS_SET_PAGE = 'LOGS_SET_PAGE';
export const LOGS_SET_FILTERSQUERY = 'LOGS_SET_FILTERSQUERY';
export const LOGS_UPDATE_FILTERING = 'LOGS_UPDATE_FILTERING';
export const LOGS_SET_SORTQUERY = 'LOGS_SET_SORTQUERY';
export const LOGS_SET_REVERSESORT = 'LOGS_SET_REVERSESORT';
export const LOGS_UPDATE_SHOWFILTERS = 'LOGS_UPDATE_SHOW_FILTERS';

//____________Users Actions_______________
export const USERS_START = 'USERS_START';
export const USERS_SUCCESS = 'USERS_SUCCESS';
export const USERS_FAIL = 'USERS_FAIL';
export const USERS_GET_ALL = 'USERS_GET_ALL';
export const USERS_SET_PAGE = 'USERS_SET_PAGE';
export const USERS_SET_PAGESIZE = 'USERS_SET_PAGESIZE';
export const USERS_SET_FILTERSQUERY = 'USERS_SET_FILTERSQUERY';
export const USERS_UPDATE_FILTERING = 'USERS_UPDATE_FILTERING';
export const USERS_SET_SORTQUERY = 'USERS_SET_SORTQUERY';
export const USERS_SET_REVERSESORT = 'USERS_SET_REVERSESORT';
export const USERS_UPDATE_SHOWFILTERS = 'USERS_UPDATE_SHOW_FILTERS';
export const USERS_SET_SELECTEDALLROWS = 'USERS_SET_SELECTEDALLROWS';
export const USERS_SELECT_USER = 'USERS_SELECT_USER';
export const USERS_UNSELECT_USER = 'USERS_UNSELECT_USER';
export const USERS_EMPTY_SELECTEDUSERS = 'USERS_EMPTY_SELECTEDUSERS';

//____________Users Actions_______________
export const SUPPLIER_REQUEST_START = 'SUPPLIER_REQUEST_START';
export const SUPPLIER_REQUEST_SUCCESS = 'SUPPLIER_REQUEST_SUCCESS';
export const SUPPLIER_REQUEST_FAIL = 'SUPPLIER_REQUEST_FAIL';
export const SUPPLIER_REQUEST_GET_ALL = 'SUPPLIER_REQUEST_GET_ALL';
export const SUPPLIER_REQUEST_SET_PAGE = 'SUPPLIER_REQUEST_SET_PAGE';
export const SUPPLIER_REQUEST_SET_PAGESIZE = 'SUPPLIER_REQUEST_SET_PAGESIZE';
export const SUPPLIER_REQUEST_SET_FILTERSQUERY = 'SUPPLIER_REQUEST_SET_FILTERSQUERY';
export const SUPPLIER_REQUEST_UPDATE_FILTERING = 'SUPPLIER_REQUEST_UPDATE_FILTERING';
export const SUPPLIER_REQUEST_SET_SORTQUERY = 'SUPPLIER_REQUEST_SET_SORTQUERY';
export const SUPPLIER_REQUEST_SET_REVERSESORT = 'SUPPLIER_REQUEST_SET_REVERSESORT';
export const SUPPLIER_REQUEST_UPDATE_SHOWFILTERS = 'SUPPLIER_REQUEST_UPDATE_SHOW_FILTERS';
export const SUPPLIER_REQUEST_SET_SELECTEDALLROWS = 'SUPPLIER_REQUEST_SET_SELECTEDALLROWS';
export const SUPPLIER_REQUEST_SELECT_USER = 'SUPPLIER_REQUEST_SELECT_USER';
export const SUPPLIER_REQUEST_UNSELECT_USER = 'SUPPLIER_REQUEST_UNSELECT_USER';
export const SUPPLIER_REQUEST_EMPTY_SELECTEDSUPPLIERS = 'SUPPLIER_REQUEST_EMPTY_SELECTEDSUPPLIERS';

//____________Users Actions_______________
export const PAYMENT_SIGNATURE_START = 'PAYMENT_SIGNATURE_START';
export const PAYMENT_SIGNATURE_SUCCESS = 'PAYMENT_SIGNATURE_SUCCESS';
export const PAYMENT_SIGNATURE_FAIL = 'PAYMENT_SIGNATURE_FAIL';
export const PAYMENT_SIGNATURE_GET_ALL = 'PAYMENT_SIGNATURE_GET_ALL';
export const PAYMENT_SIGNATURE_SET_PAGE = 'PAYMENT_SIGNATURE_SET_PAGE';
export const PAYMENT_SIGNATURE_SET_PAGESIZE = 'PAYMENT_SIGNATURE_SET_PAGESIZE';
export const PAYMENT_SIGNATURE_SET_FILTERSQUERY = 'PAYMENT_SIGNATURE_SET_FILTERSQUERY';
export const PAYMENT_SIGNATURE_UPDATE_FILTERING = 'PAYMENT_SIGNATURE_UPDATE_FILTERING';
export const PAYMENT_SIGNATURE_SET_SORTQUERY = 'PAYMENT_SIGNATURE_SET_SORTQUERY';
export const PAYMENT_SIGNATURE_SET_REVERSESORT = 'PAYMENT_SIGNATURE_SET_REVERSESORT';
export const PAYMENT_SIGNATURE_UPDATE_SHOWFILTERS = 'PAYMENT_SIGNATURE_UPDATE_SHOW_FILTERS';
export const PAYMENT_SIGNATURE_SET_SELECTEDALLROWS = 'PAYMENT_SIGNATURE_SET_SELECTEDALLROWS';
export const PAYMENT_SIGNATURE_SELECT_USER = 'PAYMENT_SIGNATURE_SELECT_USER';
export const PAYMENT_SIGNATURE_UNSELECT_USER = 'PAYMENT_SIGNATURE_UNSELECT_USER';
export const PAYMENT_SIGNATURE_EMPTY = 'PAYMENT_SIGNATURE_EMPTY';

//____________Extraction Actions_______________
export const EXTRACTION_START = 'EXTRACTION_START';
export const EXTRACTION_SUCCESS = 'EXTRACTION_SUCCESS';
export const EXTRACTION_FAIL = 'EXTRACTION_FAIL';
export const EXTRACTION_GET_ALL = 'EXTRACTION_GET_ALL';
export const EXTRACTION_SET_PAGE = 'EXTRACTION_SET_PAGE';
export const EXTRACTION_SET_PAGESIZE = 'EXTRACTION_SET_PAGESIZE';
export const EXTRACTION_SET_FILTERSQUERY = 'EXTRACTION_SET_FILTERSQUERY';
export const EXTRACTION_UPDATE_FILTERING = 'EXTRACTION_UPDATE_FILTERING';
export const EXTRACTION_SET_SORTQUERY = 'EXTRACTION_SET_SORTQUERY';
export const EXTRACTION_SET_REVERSESORT = 'EXTRACTION_SET_REVERSESORT';
export const EXTRACTION_UPDATE_SHOWFILTERS = 'EXTRACTION_UPDATE_SHOWFILTERS';
export const EXTRACTION_SET_SELECTEDALLROWS = 'EXTRACTION_SET_SELECTEDALLROWS';
export const EXTRACTION_SELECT_EXTRACTION = 'EXTRACTION_SELECT_EXTRACTION';
export const EXTRACTION_UNSELECT_EXTRACTION = 'EXTRACTION_UNSELECT_EXTRACTION';
export const EXTRACTION_EMPTY_SELECTEDEXTRACTIONS = 'EXTRACTION_EMPTY_SELECTEDEXTRACTIONS';

//-----------------INVOICEDETAIL ACTIONS-----------------
export const INVOICEDETAIL_DATA_START = 'INVOICEDETAIL_DATA_START'
export const INVOICEDETAIL_DATA_SUCCESS = 'INVOICEDETAIL_DATA_SUCCESS'
export const INVOICEDETAIL_DATA_FAIL = 'INVOICEDETAIL_DATA_FAIL'
export const INVOICEDETAIL_PDF_START = 'INVOICEDETAIL_PDF_START'
export const INVOICEDETAIL_PDF_SUCCESS = 'INVOICEDETAIL_PDF_SUCCESS'
export const INVOICEDETAIL_PDF_FAIL = 'INVOICEDETAIL_PDF_FAIL'
export const INVOICEDETAIL_EVENTS_START = 'INVOICEDETAIL_EVENTS_START'
export const INVOICEDETAIL_EVENTS_SUCCESS = 'INVOICEDETAIL_EVENTS_SUCCESS'
export const INVOICEDETAIL_EVENTS_FAIL = 'INVOICEDETAIL_EVENTS_FAIL'
export const INVOICEDETAIL_MSGS_START = 'INVOICEDETAIL_MSGS_START'
export const INVOICEDETAIL_MSGS_SUCCESS = 'INVOICEDETAIL_MSGS_SUCCESS'
export const INVOICEDETAIL_MSGS_FAIL = 'INVOICEDETAIL_MSGS_FAIL'
export const INVOICEDETAIL_SET_TAB_SIDEACTIVE = 'INVOICEDETAIL_SET_TAB_SIDEACTIVE'
export const INVOICEDETAIL_RESET_TO_INITIAL_STATE = 'INVOICEDETAIL_RESET_TO_INITIAL_STATE'
export const INVOICEDETAIL_SET_ENTITY_FILTER = 'INVOICEDETAIL_SET_ENTITY_FILTER'
export const ENTITYDETAIL_SET_ENTITY_SUCCESS = 'ENTITYDETAIL_SET_ENTITY_SUCCESS'
export const ENTITYDETAIL_GET_ENTITY_SUCCESS = 'ENTITYDETAIL_GET_ENTITY_SUCCESS'


//-----------------SUPPLIER_REQUEST DETAIL ACTIONS-----------------
export const SUPPLIERREQUESTDETAIL_DATA_START = 'SUPPLIERREQUESTDETAIL_DATA_START'
export const SUPPLIERREQUESTDETAIL_DATA_SUCCESS = 'SUPPLIERREQUESTDETAIL_DATA_SUCCESS'
export const SUPPLIERREQUESTDETAIL_DATA_FAIL = 'SUPPLIERREQUESTDETAIL_DATA_FAIL'
export const SUPPLIERREQUESTDETAIL_PDF_START = 'SUPPLIERREQUESTDETAIL_PDF_START'
export const SUPPLIERREQUESTDETAIL_PDF_SUCCESS = 'SUPPLIERREQUESTDETAIL_PDF_SUCCESS'
export const SUPPLIERREQUESTDETAIL_PDF_FAIL = 'SUPPLIERREQUESTDETAIL_PDF_FAIL'
export const SUPPLIERREQUESTDETAIL_EVENTS_START = 'SUPPLIERREQUESTDETAIL_EVENTS_START'
export const SUPPLIERREQUESTDETAIL_EVENTS_SUCCESS = 'SUPPLIERREQUESTDETAIL_EVENTS_SUCCESS'
export const SUPPLIERREQUESTDETAIL_EVENTS_FAIL = 'SUPPLIERREQUESTDETAIL_EVENTS_FAIL'
export const SUPPLIERREQUESTDETAIL_MSGS_START = 'SUPPLIERREQUESTDETAIL_MSGS_START'
export const SUPPLIERREQUESTDETAIL_MSGS_SUCCESS = 'SUPPLIERREQUESTDETAIL_MSGS_SUCCESS'
export const SUPPLIERREQUESTDETAIL_MSGS_FAIL = 'SUPPLIERREQUESTDETAIL_MSGS_FAIL'
export const SUPPLIERREQUESTDETAIL_SET_TAB_SIDEACTIVE = 'SUPPLIERREQUESTDETAIL_SET_TAB_SIDEACTIVE'
export const SUPPLIERREQUESTDETAIL_RESET_TO_INITIAL_STATE = 'SUPPLIERREQUESTDETAIL_RESET_TO_INITIAL_STATE'
export const SUPPLIERREQUESTDETAIL_SET_ENTITY_FILTER = 'SUPPLIERREQUESTDETAIL_SET_ENTITY_FILTER'
// export const ENTITYDETAIL_SET_ENTITY_SUCCESS = 'ENTITYDETAIL_SET_ENTITY_SUCCESS'
// export const ENTITYDETAIL_GET_ENTITY_SUCCESS = 'ENTITYDETAIL_GET_ENTITY_SUCCESS'
